services:
  php:
    image: docker.io/elkaouri/bracelify:v1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always
    
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - uploads_data:/app/public/images/products:Z
    tmpfs:
      - /app/var:exec 
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    env_file:
      - .env.php
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/library/postgres:16-alpine
    restart: always
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bracelify -U symfony"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  db_data:
  uploads_data:

networks:
  backend:
