services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./symfony/:/app

    tmpfs:
      - /app/var
      - /app/var/log
    environment:
      - SERVER_NAME=localhost
