FROM docker.io/dunglas/frankenphp:php8.4-bookworm


RUN apt-get update && apt-get install -y \
    unzip \
    bash \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions \
    intl \
    pdo \
    pdo_pgsql \
    opcache \
    zip 






COPY --from=docker.io/library/composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app