<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260726145541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product_collection_product (product_collection_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (product_collection_id, product_id))');
        $this->addSql('CREATE INDEX IDX_75B0F3008BA44A0F ON product_collection_product (product_collection_id)');
        $this->addSql('CREATE INDEX IDX_75B0F3004584665A ON product_collection_product (product_id)');
        $this->addSql('ALTER TABLE product_collection_product ADD CONSTRAINT FK_75B0F3008BA44A0F FOREIGN KEY (product_collection_id) REFERENCES product_collection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_collection_product ADD CONSTRAINT FK_75B0F3004584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_collection_product DROP CONSTRAINT FK_75B0F3008BA44A0F');
        $this->addSql('ALTER TABLE product_collection_product DROP CONSTRAINT FK_75B0F3004584665A');
        $this->addSql('DROP TABLE product_collection');
        $this->addSql('DROP TABLE product_collection_product');
    }
}
