name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. ÉTAPE DE VÉRIFICATION (S'exécute en PR et sur Main)
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_pgsql
          coverage: none

      - name: Install dependencies
        working-directory: symfony
        run: composer install --no-interaction --prefer-dist --no-scripts
        
      - name: Install ImportMap Assets
        working-directory: symfony
        run: php bin/console importmap:install
    
      - name: Run tests
        working-directory: symfony
        env:
          DATABASE_URL: postgresql://test:test@127.0.0.1:5432/test?serverVersion=16&charset=utf8
          KERNEL_CLASS: App\Kernel
        run: APP_ENV=test php bin/phpunit

  # 2. ÉTAPE DOCKER (Le build est testé EN PR, le push n'est fait que sur Main)
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # On ne se connecte à Docker Hub QUE si on est sur main (sécurité des secrets)
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          # TRÈS IMPORTANT : push est "true" uniquement sur main, "false" pendant la PR
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bracelify:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bracelify:v${{ github.run_number }}